### ISSUE TITLE
ModuleNotFoundError: No module named 'yunet_detector'

### ISSUE THREAD

**Issue by AaronVG99** [ros4hri/hri_face_detect#5]
Last commit does not work. 

Error:
![Screenshot from 2023-10-31 11-54-50](https://github.com/ros4hri/hri_face_detect/assets/64791842/5aa0d4e0-a03d-4a33-9357-871f06926508)

**Comment by severin-lemaignan** [comment]
Hi @AaronVG99 -- sorry for not seeing this report earlier!! do you still have the issue? the code might have changed quite a bit since then.

**Comment by FabAlert** [comment]
I have the same problem: 


`~$ roslaunch hri_face_detect detect.launch rgb_camera:=usb_cam filtering_frame:=head_camera

process[hri_face_detect-1]: started with pid [19539]
Traceback (most recent call last):
  File "/home/fabio/ros_ws/devel/lib/hri_face_detect/detect", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/fabio/ros_ws/src/hri_face_detect/scripts/detect", line 24, in <module>
    from yunet_detector import YuNetDetector
ModuleNotFoundError: No module named 'yunet_detector'
[hri_face_detect-1] process has died [pid 19539, exit code 1, cmd /home/fabio/ros_ws/devel/lib/hri_face_detect/detect image:=usb_cam/image_raw camera_info:=usb_cam/camera_info __name:=hri_face_detect __log:=/home/fabio/.ros/log/8b2c1e18-ea69-11ee-a9e3-d106cb67051d/hri_face_detect-1.log].
log file: /home/fabio/.ros/log/8b2c1e18-ea69-11ee-a9e3-d106cb67051d/hri_face_detect-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done`


How did you solve it?

**Comment by severin-lemaignan** [comment]
it looks like the `yunet_detector` module has not been compiled. How did you install `hri_face_detect`?

**Comment by thetiennguyen** [comment]
I got the same above problem, how did you solve it. I clone hri_face detect from 
https://github.com/ros4hri/hri_face_detect.git
Please help me if you fixed it already

**Comment by vignif** [comment]
https://github.com/ros4hri/hri_face_detect.git is being developed to run also on ROS2 Humble.
When cloning it to your workspace make sure to set the correct branch.

When looking into the CMakeLists.txt files of the branches I get that branches _main_ and _hri_headers_ are meant for ROS1 while _humble-devel_ is for ROS2.

I am running ROS Noetic and I got it running via cloning it with
```
git clone https://github.com/ros4hri/hri_face_detect.git -b main
```

**Comment by francescovigni** [comment]
It runs smoothly on my machine.
First make sure to use the correct branch for your system, with ROS Noetic I think the correct one is _main_ or _hri_headers_ while for ROS2 is _humble-devel_.

i.e. for ROS Noetic you can clone it like this
```
git clone https://github.com/ros4hri/hri_face_detect.git -b main
```

The problem with yunet_detector comes from where the _python binding installation is_.

You can find the location of where your binding is with

```
find devel -name "yunet_detector.*"
```

This should return something like:
```
devel/lib/yunet_detector.cpython-38-x86_64-linux-gnu.so
devel/.private/hri_face_detect/lib/yunet_detector.cpython-38-x86_64-linux-gnu.so
```

A **temporary** solution is to move the library to a folder that is actually sourced by `source devel/setup.bash` with

```
mv devel/lib/yunet_detector.cpython-38-x86_64-linux-gnu.so devel/lib/python3/dist-packages/
```
Now you can source the build with

```
source devel/setup.bash
```

and the node `detect` should run
